# Stages #
stages:
  - build

## Build Jobs ##

build_playwright:
  image: docker:24.0.7-dind-alpine3.19
  stage: build
  services:
    - docker:24.0.7-dind-alpine3.19
  variables:
      IMAGE_TAG: $CI_REGISTRY_IMAGE/playwright:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add git
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG